import React from 'react';
import { History, FileText, Download, Calendar, Filter, User } from 'lucide-react';

export const ReportsAuditLog = ({ logs }) => {
  if (!logs || logs.length === 0) {
    return (
      <div className="card-neo p-8 flex flex-col items-center justify-center text-center mt-8">
        <History size={40} className="text-gray-300 mb-3" />
        <p className="text-sm font-bold text-gray-500">No report history available.</p>
      </div>
    );
  }

  const getActionIcon = (action) => {
    if (action.includes('Generated')) return <FileText size={16} className="text-emerald-500" />;
    if (action.includes('Exported')) return <Download size={16} className="text-blue-500" />;
    if (action.includes('Scheduled')) return <Calendar size={16} className="text-purple-500" />;
    return <History size={16} className="text-gray-500" />;
  };

  const formatDate = (isoString) => {
    const d = new Date(isoString);
    return d.toLocaleString('en-US', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' });
  };

  return (
    <div className="card-neo p-6 mt-8 overflow-hidden">
      <div className="flex items-center gap-3 border-b border-gray-100 pb-4 mb-4">
        <div className="w-10 h-10 rounded-xl bg-gray-100 text-gray-600 flex items-center justify-center border border-gray-200">
          <History size={20} />
        </div>
        <div>
          <h3 className="text-lg font-black text-gray-900">Audit Logs</h3>
          <p className="text-xs text-gray-500 mt-0.5">Track report generation, exports, and schedules</p>
        </div>
      </div>

      <div className="overflow-x-auto">
        <table className="w-full text-left border-collapse min-w-[600px]">
          <thead>
            <tr className="border-b border-gray-100">
              <th className="py-3 px-4 text-[11px] font-black text-gray-400 uppercase tracking-wider">Action</th>
              <th className="py-3 px-4 text-[11px] font-black text-gray-400 uppercase tracking-wider">Report Type</th>
              <th className="py-3 px-4 text-[11px] font-black text-gray-400 uppercase tracking-wider">Filters Used</th>
              <th className="py-3 px-4 text-[11px] font-black text-gray-400 uppercase tracking-wider">Generated By</th>
              <th className="py-3 px-4 text-[11px] font-black text-gray-400 uppercase tracking-wider">Timestamp</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-50">
            {logs.map((log, index) => (
              <tr key={index} className="hover:bg-gray-50/50 transition-colors">
                <td className="py-3 px-4">
                  <div className="flex items-center gap-2">
                    {getActionIcon(log.action)}
                    <span className="text-sm font-bold text-gray-800">{log.action}</span>
                  </div>
                </td>
                <td className="py-3 px-4">
                  <span className="inline-flex items-center px-2 py-1 rounded bg-brand-primary/10 text-brand-primary text-xs font-bold">
                    {log.reportType}
                  </span>
                </td>
                <td className="py-3 px-4">
                  <div className="flex items-center gap-1 text-xs text-gray-500">
                    <Filter size={12} /> {log.filters || 'None'}
                  </div>
                </td>
                <td className="py-3 px-4">
                   <div className="flex items-center gap-2 text-xs font-medium text-gray-700">
                    <div className="w-6 h-6 rounded bg-gray-200 flex items-center justify-center"><User size={12}/></div>
                    {log.generatedBy}
                  </div>
                </td>
                <td className="py-3 px-4 text-xs font-bold text-gray-500">
                  {formatDate(log.timestamp)}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
};
