export const mockUsers = [
  {
    id: 'u1',
    name: 'Rajesh Sharma',
    memberId: 'MS-2023-0101',
    phone: '+91 9876543210',
    email: 'rajesh.sharma@example.com',
    communityName: 'Brahmin Samaj',
    city: 'Mumbai',
    state: 'Maharashtra',
    role: 'Community Head',
    registrationDate: '2023-01-15T10:30:00Z',
    isVerified: true,
    verificationStatus: 'Verified',
    accountStatus: 'Active',
    lastLogin: '2026-07-08T08:00:00Z',
    subscription: 'Premium',
    gender: 'Male',
    age: 45,
    occupation: 'Business Owner',
    bloodGroup: 'O+',
    avatar: 'https://i.pravatar.cc/150?u=u1'
  },
  {
    id: 'u2',
    name: 'Anita Desai',
    memberId: 'MS-2023-0102',
    phone: '+91 9876543211',
    email: 'anita.d@example.com',
    communityName: 'Patidar Samaj',
    city: 'Ahmedabad',
    state: 'Gujarat',
    role: 'Verified Member',
    registrationDate: '2023-02-20T14:45:00Z',
    isVerified: true,
    verificationStatus: 'Verified',
    accountStatus: 'Active',
    lastLogin: '2026-07-07T18:20:00Z',
    subscription: 'Basic',
    gender: 'Female',
    age: 38,
    occupation: 'Teacher',
    bloodGroup: 'A+',
    avatar: 'https://i.pravatar.cc/150?u=u2'
  },
  {
    id: 'u3',
    name: 'Vikram Singh',
    memberId: 'MS-2023-0103',
    phone: '+91 9876543212',
    email: 'vikram.s@example.com',
    communityName: 'Rajput Samaj',
    city: 'Jaipur',
    state: 'Rajasthan',
    role: 'Regular Member',
    registrationDate: '2023-05-10T09:15:00Z',
    isVerified: false,
    verificationStatus: 'Pending',
    accountStatus: 'Inactive',
    lastLogin: '2023-05-10T09:20:00Z',
    subscription: 'None',
    gender: 'Male',
    age: 28,
    occupation: 'Software Engineer',
    bloodGroup: 'B+',
    avatar: 'https://i.pravatar.cc/150?u=u3'
  },
  {
    id: 'u4',
    name: 'Sunita Verma',
    memberId: 'MS-2023-0104',
    phone: '+91 9876543213',
    email: 'sunita.v@example.com',
    communityName: 'Agarwal Samaj',
    city: 'Delhi',
    state: 'Delhi',
    role: 'Volunteer',
    registrationDate: '2023-06-01T11:00:00Z',
    isVerified: true,
    verificationStatus: 'Verified',
    accountStatus: 'Suspended',
    lastLogin: '2026-06-15T10:00:00Z',
    subscription: 'Basic',
    gender: 'Female',
    age: 52,
    occupation: 'Homemaker',
    bloodGroup: 'AB+',
    avatar: 'https://i.pravatar.cc/150?u=u4'
  },
  {
    id: 'u5',
    name: 'Amit Patel',
    memberId: 'MS-2023-0105',
    phone: '+91 9876543214',
    email: 'amit.p@example.com',
    communityName: 'Patidar Samaj',
    city: 'Surat',
    state: 'Gujarat',
    role: 'Donor',
    registrationDate: '2023-08-22T16:30:00Z',
    isVerified: true,
    verificationStatus: 'Verified',
    accountStatus: 'Active',
    lastLogin: '2026-07-08T07:45:00Z',
    subscription: 'Lifetime',
    gender: 'Male',
    age: 60,
    occupation: 'Industrialist',
    bloodGroup: 'O-',
    avatar: 'https://i.pravatar.cc/150?u=u5'
  }
];
